from pathlib import Path
p=Path('index.html')
s=p.read_text(errors='ignore')
old_t="for(const [name,x,y] of towns){if(!inside([x,y]))continue;parts.push(`<circle cx=\"${sx(x).toFixed(1)}\" cy=\"${sy(y).toFixed(1)}\" r=\"2.3\" fill=\"#173d49\"/><text x=\"${(sx(x)+5).toFixed(1)}\" y=\"${(sy(y)-4).toFixed(1)}\" fill=\"#173d49\" font-size=\"9.5\" font-weight=\"750\" filter=\"url(#labelhalo)\">${name}</text>`)}"
new_t="if(isVermont)for(const [name,x,y] of towns){if(!inside([x,y]))continue;parts.push(`<circle cx=\"${sx(x).toFixed(1)}\" cy=\"${sy(y).toFixed(1)}\" r=\"2.3\" fill=\"#173d49\"/><text x=\"${(sx(x)+5).toFixed(1)}\" y=\"${(sy(y)-4).toFixed(1)}\" fill=\"#173d49\" font-size=\"9.5\" font-weight=\"750\" filter=\"url(#labelhalo)\">${name}</text>`)}"
if old_t not in s: raise SystemExit('town loop owner not found')
s=s.replace(old_t,new_t,1)
old_c='Figure 1. Technical screening map generated by the Earthline search engine from the frozen published geometry for this run. Gray lines are modeled contours, blue lines are modeled surface-water paths, translucent blue outlined areas are mapped aquifer context where verified geometry is available, and green/gold/orange lines are graded opportunity corridors. The figure does not rely on a camera screenshot or camera-scoped context raster.'
new_c='Figure 1. Technical screening map generated by the Earthline search engine from the frozen published geometry for this run. Gray lines are modeled contours with sparse elevation labels in metres where numeric contour elevation is present, blue lines are modeled surface-water paths, translucent blue outlined areas are mapped aquifer context where verified geometry is available, and green/gold/orange lines are graded opportunity corridors. The figure does not rely on a camera screenshot or camera-scoped context raster.'
if old_c not in s: raise SystemExit('Figure 1 caption owner not found')
s=s.replace(old_c,new_c,1)
p.write_text(s)