from pathlib import Path

p=Path('index.html')
s=p.read_text(errors='ignore')

anchor="const replacements16941=["
if anchor not in s:
    raise SystemExit('replacements16941 owner not found')

extra="""const replacements16941=[
            ["When rain falls on sloped ground, most of it does not soak in. It sheets downhill, gathers into rivulets, then into channels, and leaves the property within hours.","When rainfall exceeds the ground’s infiltration capacity on sloped land, some water moves downslope as runoff. It can gather into rivulets and channels and leave the site quickly."],
            ["In late summer, there is too little. A stream between rainstorms is not fed by rain. It is fed by groundwater slowly seeping into the channel from the surrounding land — a flow called baseflow. Land that sheds its rain quickly has little stored to give back. The well runs low, the brook runs thin, and the pasture browns first.","During dry periods, streamflow is often sustained by groundwater and other delayed subsurface contributions called baseflow. Landscapes that store less water have less available to release between storms, which can contribute to low streamflow, dry soils, and stressed wells."],
            ["Both problems have the same cause: the water moved too fast to be kept.","Both conditions can be worsened when water leaves the landscape faster than it can be stored."],
            ["These are not two problems. They are one problem, arriving in two seasons.","Flood peaks and dry-season shortages are closely linked to how a watershed stores and releases water over time."],
            ["A bioswale is a shallow, planted trench dug along the contour of a slope — level from end to end, so water cannot run along it.","In Earthline’s use, a bioswale is a shallow, planted contour trench intended to interrupt downslope runoff and spread it along a nearly level alignment."],
            ["Water running downhill meets the trench and stops. Held there, it does the one thing runoff never does: it waits. And while it waits, it soaks downward through the soil.","Runoff reaching the swale slows and can temporarily pond. The added residence time creates an opportunity for infiltration instead of immediate downslope conveyance."],
            ["Sink it. Standing water infiltrates. It passes down through soil and rock and joins the groundwater below — the saturated zone that feeds wells and springs.","Sink it. Ponded water has time to infiltrate. Some remains in the soil and root zone; some may move deeper and, where local hydrogeology allows, contribute to groundwater recharge."],
            ["This is old technology. Contour water-harvesting earthworks appear independently in Andean, South Asian, North African, and Southwestern Indigenous agriculture, in some cases for thousands of years. Earthline did not invent this method. It locates where the method applies.","Contour water-harvesting has long precedents in Andean, South Asian, North African, and Southwestern Indigenous land-management traditions. Earthline did not invent the method; it screens landscapes for places where the underlying hydrologic principle may be useful."],
            ["Water that infiltrates does not stay under the swale. It moves — slowly, underground, downhill — along paths that can run for hundreds of meters or many kilometres, and it eventually re-emerges. It surfaces in springs, in wetlands, and in stream channels, where it becomes the baseflow that keeps water moving in dry weather.","Infiltrated water can remain in the root zone, move laterally through shallow subsurface layers, or travel deeper along groundwater flow paths. Where those paths connect to springs, wetlands, or streams, part of that water can later contribute to baseflow."],
            ["The transit is slow by design. Groundwater on longer, deeper paths spends more time in the subsurface than groundwater on short shallow ones. That delay is the entire benefit: rain that would have left in six hours instead leaves over weeks or months, arriving when the landscape needs it rather than when it can least use it.","Longer subsurface pathways can increase residence time. That delay is one major benefit of infiltration-based retention: some water that might have become rapid runoff can instead remain in the landscape and be released more slowly."],
            ["Water intercepted near the bottom of a slope has almost no landscape left to travel through. It infiltrates and re-emerges a short distance later.","Water intercepted low on a slope may have a shorter subsurface path before reaching a discharge area, depending on local geology and groundwater gradients."],
            ["Water intercepted higher up enters a longer flow path. It travels farther underground, stays stored longer, and re-emerges further down the system — supporting soil moisture, springs, wells, and stream baseflow across everything between the recharge point and the discharge point.","In many hillslope settings, water infiltrated higher on a slope can enter longer subsurface pathways and remain stored longer before discharge. The actual path and travel time depend on soils, bedrock, fractures, and groundwater gradients."],
            ["A bioswale is not an addition to a natural system. It is a partial replacement for retention that was industrially removed from this watershed roughly four centuries ago and never restored. The comparison is not intervention versus untouched nature. It is intervention versus a landscape already stripped of most of its capacity to hold water.","The northeastern beaver record is a historical example of how land-use change can remove distributed water storage. A bioswale does not recreate a beaver wetland; it uses the same broad principle of slowing water and increasing residence time on appropriate hillslopes."],
            ["Beavers held the channels. Deep forest soils and their organic layers held the hillslopes. Trapping removed the first; clearing, grazing, and compaction degraded the second. Bioswales address the hillslope half — and they rebuild it, because a swale re-waters ground where native trees and vegetation can be planted back, that vegetation drops organic material that becomes mulch and then new soil, and roots and berm together retain the soil that would otherwise be washed downstream.","In forested landscapes, channel storage, deep soils, organic layers, and root networks all contribute to slowing and storing water. On suitable hillslopes, planted swales can complement those functions by retaining runoff, supporting vegetation, and reducing soil loss."],
            ["Groundwater recharge is why Earthline ranks a corridor. It is not the only thing the corridor does.","Groundwater-recharge potential is a central consideration in Earthline’s corridor ranking, but it is not the only landscape function that matters."],
            ["Cuts the flood peak. Retention structures reduced peak flows by up to 74% in monitored field studies — the water still arrives, just later and lower.","Can reduce peak runoff under appropriate conditions. Related monitored bioretention systems have reported peak-flow reductions up to 74%, but those values are not a performance prediction for a contour swale."],
            ["Recharges groundwater — the wells, springs, and dry-season stream flow that a landscape lives on.","Creates opportunities for infiltration and, where hydrogeology permits, groundwater recharge that can support wells, springs, and dry-season streamflow."],
            ["Extends baseflow into late summer by converting a six-hour runoff event into weeks or months of slow subsurface release.","Can support longer-term subsurface storage and baseflow where infiltrated water connects to groundwater and stream systems."],
            ["Works through frozen ground. In cold climates, 45–100% of depression-focused recharge occurred while the soil was still partly frozen.","Infiltration can continue during partial freeze conditions where connected macropores remain open; field studies have measured substantial depression-focused recharge before complete thaw."],
            ["Captures snowmelt that would otherwise run off. Ground with intact root structure sheds roughly half as much snowmelt as compacted ground.","Can capture part of snowmelt runoff. Field observations show that intact root structure and macropores can substantially increase frozen-soil infiltration relative to compacted or cultivated ground."],
            ["Builds new soil. Re-watered ground supports planting; planting drops organic material; organic material becomes mulch and then soil. The structure improves every year instead of degrading.","Can support soil-building processes. Re-watered ground can support vegetation, litter accumulation, root growth, and reduced erosion when the planting and maintenance are appropriate."],
            ["Reforests. A swale makes tree establishment viable on ground too dry or too eroded to support it — and the trees then do the hydrological work.","Can support tree establishment on suitable degraded ground; once established, woody roots can further improve soil structure and infiltration pathways."],
            ["Installs permanent underground plumbing. Tree roots build macropores that persist after the root decays. Conductivity under trees has measured 2 to 140 times that of adjacent pasture.","Develops persistent root-driven macropores. Woody roots can create preferential-flow pathways that persist after roots decay; measured conductivity under trees has exceeded adjacent pasture in multiple studies."],
            ["Corrects the soil while it works. Nitrogen-fixing and deep-rooted species chosen for the site address the deficiency that made it degraded in the first place.","Can improve soil function when vegetation is selected for the site. Nitrogen-fixing or deep-rooted species may address specific deficiencies, but that is a design choice rather than an automatic outcome."],
            ["Cleaner water reaches the aquifer when it enters high on a slope — a smaller contributing area means fewer contaminant sources upstream, and a thicker unsaturated zone means more filtration on the way down.","Water quality at a recharge point depends on the contributing area, contaminant sources, soil, and hydrogeology. Smaller clean contributing areas and thicker unsaturated zones can reduce some risks, but they do not guarantee clean recharge."],
            ["Root channels are the mechanism.","Root channels are one important infiltration mechanism."],
            ["In a cold climate, snowmelt is the dominant recharge event of the year. The surprising finding is that swales work while the ground is still frozen.","In many cold-climate watersheds, snowmelt is a major recharge period. Field studies show that infiltration can continue while soil is partly frozen when connected macropores remain open."],
            ["Two independent mechanisms make the same volume of recharge cleaner when it enters high on a slope.","Two site factors can influence recharge-water quality: the contributing area above the infiltration point and the thickness and properties of the unsaturated zone."],
            ["A swale intercepting salted road runoff is not a recharge asset. It is an injection pathway to the aquifer.","A swale intercepting heavily salted road runoff should not be treated as a recharge asset; preferential infiltration can move chloride toward groundwater."],
            ["Peak stage is what floods a village. Not total volume — the crest. Water that arrives over three days instead of six hours produces a lower crest, and a lower crest means less bank scour, less channel incision, and less property under water.","Flood damage is strongly influenced by peak stage — the crest — together with duration and local hydraulics. Spreading runoff arrival over more time can lower the crest and reduce erosive stress."],
            ["Reconnecting floodplains works — where the river is flat enough. A levee setback on the Missouri River is estimated to reduce 100-year flood stages by 0.1–0.5 m. (modeled)","Floodplain reconnection can reduce flood stage where valley geometry allows. A modeled Missouri River levee setback reduced estimated 100-year flood stages by 0.1–0.5 m."],
            ["And here is the finding that matters in mountain country. Flood attenuation on a floodplain depends strongly on slope, and it is often the single most important variable. On steeper rivers, gravity dominates flood-wave propagation and floodplain attenuation is minimal.","In mountain settings, valley slope is a strong control on flood-wave attenuation. As slope increases, floodplain storage may provide less attenuation and distributed upstream retention becomes more relevant."],
            ["These figures come from urban bioretention cells with filter media, underdrains, and defined inlets. A contour swale is simpler and unlined. Read them as the upper bound of what the mechanism can achieve, not as a prediction for this property.","These figures come from urban bioretention cells with filter media, underdrains, and defined inlets. A contour swale is simpler and unlined. Treat the figures as evidence that infiltration-based detention can alter runoff, not as a prediction or performance bound for a contour swale."],
"""
s=s.replace(anchor,extra,1)

walker="while((tn=walker.nextNode())){let t=tn.nodeValue||'';for(const pair of replacements16941)t=t.split(pair[0]).join(pair[1]);tn.nodeValue=t;}"
if walker not in s:
    raise SystemExit('How Swales text walker not found')
cleanup=walker+"[...bh.querySelectorAll('p')].forEach(el=>{if(/^On soil carbon — a caution\./.test(String(el.textContent||'').trim()))el.remove();});"
s=s.replace(walker,cleanup,1)

p.write_text(s)
