from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(errors='ignore')

# Remove decorative grid: professional plan figure should let the actual landform carry the page.
s=re.sub(r"\s*for\(let i=1;i<6;i\+\+\)parts\.push\([^;]+stroke=\"#c6d1cb\"[^;]+;",'',s,count=1)

# Professional visual hierarchy; no analysis coordinates or classifications change.
pairs=[
 ('stroke="#7d8982" stroke-width=".50" opacity=".30"','stroke="#8e9387" stroke-width=".58" opacity=".42"'),
 ('fill="#eef2ef" fill-opacity=".88"','fill="#f7f5ed" fill-opacity=".94"'),
 ('fill="#536a66" font-size="${small?6.8:7.4}"','fill="#55655f" font-size="${small?7.0:7.8}"'),
 ('stroke="#ffffff" stroke-width="1.65" opacity=".46"','stroke="#fffdfa" stroke-width="3.2" opacity=".88"'),
 ('stroke="#087bb4" stroke-width="1.45" opacity=".92"','stroke="#087bb4" stroke-width="1.65" opacity=".97"'),
 ("mainW=r.grade==='A'?2.2:r.grade==='B'?1.7:1.25,haloW=mainW+1.15,alpha=r.grade==='A'?'.9':r.grade==='B'?'.77':'.48'","mainW=r.grade==='A'?3.8:r.grade==='B'?3.2:2.65,haloW=mainW+2.2,alpha=r.grade==='A'?'.98':r.grade==='B'?'.9':'.74'"),
 ('font-size="13" font-weight="800">${title}</text>','font-size="15" font-weight="850">${title}</text>')
]
for a,b in pairs:
    if a in s:s=s.replace(a,b,1)

s=s.replace('fill="rgba(43,132,199,.27)"','fill="rgba(43,132,199,.22)"',1)
s=s.replace("stroke-width=\"'+(small?1.9:2.4)+'\"","stroke-width=\"'+(small?2.0:2.65)+'\"",1)
s=s.replace('width="112" height="21"','width="130" height="22"',1)
s=s.replace('(sx(lng)-56).toFixed(1)','(sx(lng)-65).toFixed(1)',1)
s=s.replace('(sy(lat)-12).toFixed(1)','(sy(lat)-12.5).toFixed(1)',1)
s=s.replace('font-size="8.7" font-weight="850"','font-size="9.2" font-weight="850"',1)

old="const title='Earthline '+(reportPlace?reportPlace+' ':'')+(reportTier==='focus'?'focus':'regional')+' screening map';"
new="const title='Earthline Screening Map'+(reportPlace?' · '+reportPlace:'')+' · '+(reportTier==='focus'?'Focus':'Regional');"
if old in s:s=s.replace(old,new,1)

oldcap='Figure 1. Technical screening map generated by the Earthline search engine from the frozen published geometry for this run. Gray lines are modeled contours with sparse elevation labels in metres where numeric contour elevation is present, blue lines are modeled surface-water paths, translucent blue outlined areas are mapped aquifer context where verified geometry is available, and green/gold/orange lines are graded opportunity corridors. The figure does not rely on a camera screenshot or camera-scoped context raster.'
newcap='Figure 1. Earthline screening map for this run. Green, gold, and rust lines are graded bioswale-opportunity corridors; blue lines are modeled surface-water paths; translucent blue areas show mapped aquifer context; contours and elevation labels show landform. Geometry is the frozen published output for this run. Screening only; field verification is required before design.'
if oldcap in s:s=s.replace(oldcap,newcap,1)

p.write_text(s)