from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
old='''  const f=earthlineSelectPlaceCandidate16537(q,j.features);\n  if(!f)return null;\n  const zh=PLACE_ZOOM[(f.place_type&&f.place_type[0])||"place"]||15;\n'''
new='''  let f=earthlineSelectPlaceCandidate16537(q,j.features);\n  if(!f)return null;\n  /* EARTHLINE 16846 — global country-name ambiguity fallback. If a short bare\n     query resolves to an identically named non-country result, ask the same\n     geocoder once for countries only. The country fallback is accepted only when\n     the country name is exact or has high relevance plus the same word count and\n     a shared substantive token. This admits close exonyms such as Cabo/Cape Verde\n     while rejecting unrelated low-relevance countries such as Chiang Mai/Mali.\n     Addresses, comma-qualified searches and ordinary qualified place searches\n     keep the existing single-query path. */\n  const bareCountryCheck16846=!/[0-9,@]/.test(String(q||''))&&earthlinePlaceKey16537(q).split(/\\s+/).filter(Boolean).length<=4;\n  const queryKey16846=earthlinePlaceKey16537(q),selectedType16846=earthlinePlaceType16537(f),selectedName16846=earthlinePlaceKey16537(f.text||String(f.place_name||'').split(',')[0]);\n  if(bareCountryCheck16846&&selectedType16846!=='country'&&selectedName16846===queryKey16846){\n    try{\n      const countryUrl16846="https://api.mapbox.com/geocoding/v5/mapbox.places/"+encodeURIComponent(earthlinePlaceLookupQuery16541(q))+".json?limit=5&types=country&language=en&access_token="+MAPBOX_TOKEN;\n      const countryResponse16846=await fetch(countryUrl16846);\n      if(earthlineIsStale(myGen))return null;\n      if(countryResponse16846.ok){\n        const countryJson16846=await countryResponse16846.json();\n        if(earthlineIsStale(myGen))return null;\n        const countryCandidate16846=earthlineSelectPlaceCandidate16537(q,countryJson16846&&countryJson16846.features||[]);\n        if(countryCandidate16846&&earthlinePlaceType16537(countryCandidate16846)==='country'){\n          const countryName16846=earthlinePlaceKey16537(countryCandidate16846.text||String(countryCandidate16846.place_name||'').split(',')[0]);\n          const queryTokens16846=queryKey16846.split(/\\s+/).filter(Boolean),countryTokens16846=countryName16846.split(/\\s+/).filter(Boolean);\n          const sharedSubstantive16846=queryTokens16846.some(t16846=>t16846.length>=4&&countryTokens16846.includes(t16846));\n          const relevance16846=Math.max(0,Math.min(1,Number(countryCandidate16846.relevance)||0));\n          const acceptableCountry16846=countryName16846===queryKey16846||(relevance16846>=0.85&&queryTokens16846.length===countryTokens16846.length&&sharedSubstantive16846);\n          if(acceptableCountry16846)f=countryCandidate16846;\n        }\n      }\n    }catch(_){ }\n  }\n  const zh=PLACE_ZOOM[(f.place_type&&f.place_type[0])||"place"]||15;\n'''
if old not in s:
    raise SystemExit('16846 geocoder fallback anchor not found')
if 'bareCountryCheck16846' in s:
    raise SystemExit('16846 geocoder fallback already present')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('patched geocoder: EARTHLINE 16846 guarded country-only ambiguity fallback')
