from pathlib import Path
p=Path('earthline-launch-16872.js')
s=p.read_text(encoding='utf-8')
old="function scheduleTranslation(){for(const ms of [0,80,260,700,1400])setTimeout(translateVisibleText,ms)}"
new="function scheduleTranslation(){for(const ms of [0,80,260,700,1400,2200,3200])setTimeout(translateVisibleText,ms)}"
if s.count(old)!=1: raise SystemExit(f'scheduleTranslation anchor count {s.count(old)}')
s=s.replace(old,new)
old2="function donateTarget(){try{return String(window.EARTHLINE_DONATE_URL_16872||localStorage.getItem('earthlineDonateUrl16872')||'')}catch(_){return String(window.EARTHLINE_DONATE_URL_16872||'')}}\nfunction donate(){track('donate_click');const u=donateTarget();if(u){window.open(u,'_blank','noopener');return}window.open('donate.html','_blank','noopener')}"
new2="function donateTarget(){try{return String(window.EARTHLINE_DONATE_URL_16872||localStorage.getItem('earthlineDonateUrl16872')||'')}catch(_){return String(window.EARTHLINE_DONATE_URL_16872||'')}}\nfunction merchTarget(){try{return String(window.EARTHLINE_MERCH_URL_16872||localStorage.getItem('earthlineMerchUrl16872')||'')}catch(_){return String(window.EARTHLINE_MERCH_URL_16872||'')}}\nfunction donate(){track('donate_click');const u=donateTarget();if(u)window.open(u,'_blank','noopener')}"
if s.count(old2)!=1: raise SystemExit(f'donate anchor count {s.count(old2)}')
s=s.replace(old2,new2)
old3="function installRail(){if(document.getElementById('earthlineLaunchLogin16872'))return;const rail=document.getElementById('earthlineRail16188');const contact=document.getElementById('earthlineRailContact16512');const host=rail||contact?.parentElement||document.body;const mk=(id,txt)=>{const b=document.createElement('button');b.id=id;b.type='button';b.className=(rail?'el-rail-control-16188 ':'')+'earthline-launch-rail-btn-16872';b.textContent=txt;b.setAttribute('aria-label',txt);return b};const L=mk('earthlineLaunchLogin16872',t().login),D=mk('earthlineLaunchDonate16872',t().donate),M=mk('earthlineLaunchMerch16872',t().merch);L.onclick=()=>openAccount('login');D.onclick=donate;M.onclick=()=>{track('merch_click');window.open('merchandise.html','_blank','noopener')};if(rail){rail.append(L,D,M)}else if(contact){host.append(L,D,M)}else{const wrap=document.createElement('div');wrap.id='earthlineLaunchFallbackRail16872';wrap.append(L,D,M);document.body.appendChild(wrap)}renderAccount()}"
new3="function installRail(){if(document.getElementById('earthlineLaunchLogin16872'))return;const rail=document.getElementById('earthlineRail16188');const contact=document.getElementById('earthlineRailContact16512');const host=rail||contact?.parentElement||document.body;const mk=(id,txt)=>{const b=document.createElement('button');b.id=id;b.type='button';b.className=(rail?'el-rail-control-16188 ':'')+'earthline-launch-rail-btn-16872';b.textContent=txt;b.setAttribute('aria-label',txt);return b};const L=mk('earthlineLaunchLogin16872',t().login),D=donateTarget()?mk('earthlineLaunchDonate16872',t().donate):null,M=merchTarget()?mk('earthlineLaunchMerch16872',t().merch):null;L.onclick=()=>openAccount('login');if(D)D.onclick=donate;if(M)M.onclick=()=>{track('merch_click');window.open(merchTarget(),'_blank','noopener')};const items=[L,D,M].filter(Boolean);if(rail){rail.append(...items)}else if(contact){host.append(...items)}else{const wrap=document.createElement('div');wrap.id='earthlineLaunchFallbackRail16872';wrap.append(...items);document.body.appendChild(wrap)}renderAccount()}"
if s.count(old3)!=1: raise SystemExit(f'installRail anchor count {s.count(old3)}')
s=s.replace(old3,new3)
old4="window.EARTHLINE_LAUNCH_16872={build:BUILD,quota,consumePaidSearch,createAccount,signIn,signOut,openAccount,donateTarget,limits:()=>({...config}),isConfiguredDonation:()=>!!donateTarget(),translateVisibleText,centralClaim,track,refreshSessionIfNeeded};"
new4="window.EARTHLINE_LAUNCH_16872={build:BUILD,quota,consumePaidSearch,createAccount,signIn,signOut,openAccount,donateTarget,merchTarget,limits:()=>({...config}),isConfiguredDonation:()=>!!donateTarget(),isConfiguredMerch:()=>!!merchTarget(),translateVisibleText,centralClaim,track,refreshSessionIfNeeded};"
if s.count(old4)!=1: raise SystemExit(f'export anchor count {s.count(old4)}')
s=s.replace(old4,new4)
p.write_text(s,encoding='utf-8')
print('patched exact launch file: bounded language settle + withheld unconfigured Donate/Merch')